### ISSUE TITLE
File "E:\Anaconda3\envs\IGMC-master\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main     raise RuntimeError

### ISSUE THREAD

**Issue by JiyangXu0427** [muhanzhang/IGMC#11]
Dear Dr.Zhang

First I'd like to say big thanks to this great work and the paper.

I tried to run this program on my windows pc.
After I run "python Main.py --data-name yahoo_music **--epochs 1** --testing --ensemble" in the PyCharm terminal (as well on douban and flixster dataset) , the program always got finally stuck at a place, raising runtime error like below: 
![image](https://user-images.githubusercontent.com/62331568/102557332-fe86bf00-411e-11eb-8467-74d6b75b90dc.png)

And the data folder ended as empty, but files were generated under results folder
![image](https://user-images.githubusercontent.com/62331568/102557881-4ce88d80-4120-11eb-8a65-aeb3b13c78a1.png)

![image](https://user-images.githubusercontent.com/62331568/102557999-95a04680-4120-11eb-8e67-5e8fcc04c21a.png)

Part of the output from the terminal was copied into a google doc, and from the output can see that this runtime error happens all the way during the program running, however, only got stuck at the last place.
https://docs.google.com/document/d/1EV-qGCuVi0t6q-jh1K5Dvnj9UASOLYq-djh6lD8FM7g/edit?usp=sharing

The python and torch environment can be seen in below picture
![image](https://user-images.githubusercontent.com/62331568/102557759-04c96b00-4120-11eb-9a54-2ac62244c0ca.png)

I will try to run it again under the Python 3.8.1 + PyTorch 1.4.0 + PyTorch_Geometric 1.4.2. environment to see what will happen.

Thanks so much and best regards
Jiyang

**Comment by muhanzhang** [comment]
Hi! It seems to be caused by windows' multiprocessing. Can you turn off multiprocessing by setting "parallel=False" in this [line](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/util_functions.py#L71)?

**Comment by JiyangXu0427** [comment]
> 
> 
> Hi! It seems to be caused by windows' multiprocessing. Can you turn off multiprocessing by setting "parallel=False" in this [line](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/util_functions.py#L71)?


Dear Dr.Zhang

I made the attempt to set it as False at that line, and run again in the Pytorch 1.6 enviroment, the same runtime error happens again, but this time, much quicker, right after few lines of output in the terminal. Not like yesterday which was after tons of lines of output. And even the time counter disappeared this time.
So I also tried to set the parallel as False in [https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/util_functions.py#L158](url)
but still run into the same error.
![image](https://user-images.githubusercontent.com/62331568/102578522-76201280-414e-11eb-87a4-863653c4b889.png)

The whole output from the terminal is here
https://docs.google.com/document/d/1cbRrfoZC-jOtryl2DswszfLFX5-QzuOHliW4dNuvPQo/edit?usp=sharing

**Comment by muhanzhang** [comment]
I found this possible issue. It was because the dataloader by default also used two workers. Can you set "num_workers = 0" in this [line](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/train_eval.py#L43) and this [line](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/train_eval.py#L49)?

**Comment by JiyangXu0427** [comment]
> 
> 
> I found this possible issue. It was because the dataloader by default also used two workers. Can you set "num_workers = 0" in this [line](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/train_eval.py#L43) and this [line](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/train_eval.py#L49)?
> 
> 

Dear Dr.Zhang

Big big thanks for the solution! Really save my life!
Now the program can run and the graph can be generated successfully!
![image](https://user-images.githubusercontent.com/62331568/102611453-0b3cfe80-4183-11eb-9a0b-2bdcc35f9178.png)


Although at last stage the output show one FileNotFoundError like below, I think for this one I might be able to figure it out.
![image](https://user-images.githubusercontent.com/62331568/102611591-4dfed680-4183-11eb-8577-c11c3e9b9e58.png)

So many thanks for the solution and the paper.
