### ISSUE TITLE
OSError: [WinError 126] module could not be found

### ISSUE THREAD

**Issue by Oweys-Mo** [muhanzhang/IGMC#12]
Hello,

I tried running
`python Main.py --data-name flixster --epochs 40 --testing --ensemble`

and got:

> File "Main.py", line 11, in <module>
>     from util_functions import *
>   File "C:\Users\PCOvice\Downloads\IGMC-master\IGMC-master\util_functions.py", line 13, in <module>
>     from torch_geometric.data import Data, Dataset, InMemoryDataset
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
>     import torch_geometric.nn
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
>     from .data_parallel import DataParallel
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
>     from torch_geometric.data import Batch
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
>     from .data import Data
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch_geometric\data\data.py", line 8, in <module>
>     from torch_sparse import coalesce, SparseTensor
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch_sparse\__init__.py", line 13, in <module>
>     library, [osp.dirname(__file__)]).origin)
>   File "C:\Users\PCOvice\anaconda3\lib\site-packages\torch\_ops.py", line 105, in load_library
>     ctypes.CDLL(path)
>   File "C:\Users\PCOvice\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found
> 

Does someone know how to solve that?

Thank you in advance

**Comment by muhanzhang** [comment]
Hi, from the message, it seems to be an issue about the installation of torch_sparse. Are you able to "import torch_sparse" in python directly? If not, you may try to reinstall torch_sparse and torch_geometric.

**Comment by Oweys-Mo** [comment]
Thank you.
Reinstallation worked.
