### ISSUE TITLE
Dealing with large graph

### ISSUE THREAD

**Issue by suhmily** [muhanzhang/IGMC#14]
I met same problem with #9  on large graph , related code in preprocessing.py on line 156:
labels = np.full((num_users, num_items), neutral_rating, dtype=np.int32)
Could you please give some suggestions? Thanks.

**Comment by muhanzhang** [comment]
Hi! Thanks for raising this issue. I have updated the repo in [commit](https://github.com/muhanzhang/IGMC/commit/f895697bb6e79d36e36eb1b2380d4e63594adfd5) by removing this dense label matrix and switching to more memory-efficient operations. Please have a try and let me know if it works.
