### ISSUE TITLE
Can you share the comparison method code?

### ISSUE THREAD

**Issue by kongbo96** [muhanzhang/IGMC#15]
Such as the implement of PinSage.

**Comment by muhanzhang** [comment]
Hi! We decided not to share the implementations of the baselines, as it is beyond our capability to maintain them and answer the related questions. But I can share how we implement PinSage: we directly modified the GC-MC tensorflow code, by replacing its one-hot features with node content features (if any) or node degrees. We didn't adopt PinSage's original random-walk based sampling method, as our graphs are not large; all nodes use GCN to aggregate their neighbors directly. We also did some modifications to adapt PinSage to rating prediction.

**Comment by kongbo96** [comment]
I don't think it's necessarily suitable for scoring prediction tasks because it's specifically for topn tasks. So I wanted to see how you do it before. If it's not convenient, can you tell me where I can find its original code?

**Comment by muhanzhang** [comment]
PinSage is an industry product that depends on Pinterest's specific infra. To my knowledge, there isn't an official open-sourced version.
