### ISSUE TITLE
Performances on ML-100k

### ISSUE THREAD

**Issue by sclincha** [muhanzhang/IGMC#19]
Hi,
 Thanks for sharing your code and your interesting paper.
 I could not install the prior version of pytorch geometric on my machine but I did install

torch==1.7.0
torch-cluster==1.5.8
torch-geometric==1.6.3
torch-scatter==2.0.5
torch-sparse==0.6.8
and then fix the code in train_eval.py by updating the attributes names  by

```
-                    gconv.att,
-                    gconv.basis.view(gconv.num_bases, -1)
+                    gconv.comp,
+                    gconv.weight.view(gconv.num_bases, -1)

```

Then, I launched the command on ml_100k (without dynamic train to speed up the training)

```
python Main.py --data-name ml_100k --save-appendix _mnph200 --data-appendix _mnph200 --epochs 80 --max-nodes-per-hop 200 --testing --ensemble

Epoch 80, train loss 0.847587, test rmse 0.921295:  99%|██████████████████████████████████████████████████████▎| 79/80 [4:13:22<03:10, 190.49s/it]Saving model states...
Epoch 80, train loss 0.847587, test rmse 0.921295: 100%|███████████████████████████████████████████████████████| 80/80 [4:13:22<00:00, 190.03s/it]

Test Once RMSE: 0.922065, Duration: 72.088108
```

However, the performance is much lower compared to the ones reported in the paper. Is there any additional hyperparameters to change ? Have you tried your code with more recent torch and torch_geometric installation ?

Thanks for your help !

**Comment by muhanzhang** [comment]
Yes. I have observed similar performance gaps using more recent pyg versions. I haven't found the exact reasons. Tuning the hyperparameters help. For example, you can 1) turn off the ARR regularization by "--ARR 0", 2) increase the hop to 2 by "--hop 2", and 3) remove the "--max-nodes-per-hop 200" restriction. All of these seem to increase the performance, and the combination seems to be able to improve the ML100K score to 0.905.

**Comment by sclincha** [comment]
Ok thanks ! Tried your recommendations but reach only  0.913. Will play a little bit more.

Thanks
