### ISSUE TITLE
Not able to reproduce results

### ISSUE THREAD

**Issue by vascobailao** [muhanzhang/IGMC#2]
```
Traceback (most recent call last):
  File "Main.py", line 338, in <module>
    multiply_by=multiply_by)
  File "/Users/vasfern/Downloads/IGMC-master/models.py", line 146, in __init__
    super(IGMC, self).__init__(dataset, GCNConv, latent_dim, regression, adj_dropout, force_undirected)
  File "/Users/vasfern/Downloads/IGMC-master/models.py", line 20, in __init__
    self.convs.append(gconv(dataset.num_features, latent_dim[0]))
  File "/Users/vasfern/Downloads/IGMC-master/.venv/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 117, in num_features
    return self.num_node_features
  File "/Users/vasfern/Downloads/IGMC-master/.venv/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 112, in num_node_features
    return self[0].num_node_features
  File "/Users/vasfern/Downloads/IGMC-master/.venv/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 188, in __getitem__
    data = self.get(self.indices()[idx])
TypeError: 'tuple' object is not callable
```

**Comment by muhanzhang** [comment]
Hi, which PyG version did you use? I originally thought this might be caused by that you are using the latest PyG version. But I have tested with PyG 1.4.2 + PyTorch 1.4 + Python 3.8, and it worked fine. Also, which command did you execute?

**Comment by muhanzhang** [comment]
Hi, I have found the reason. So you have used the "--dynamic-dataset" option. This option instantiates a MyDynamicDataset object defined in util_functions.py. The latest Pytorch_Geometric changes some of its Dataset class functions (the self.indices() had the same name as one of MyDaynamicDataset's attributes). Now I have fixed this issue by renaming this attribute. Please pull the latest changes and try again and it should work!

**Comment by Lim-Sung-Jun** [comment]
I have a same problem, train_graph does not make num_features used on "self.convs.append(gconv(dataset.num_features, latent_dim[0]))"

the code is on GNN class

I'm using the latest pyG version now because the pyG 1.4.2 version is not available.

could you give me some advice?

**Comment by muhanzhang** [comment]
@Lim-Sung-Jun Sorry I did not get you. Could you restate your question and provide instructions for reproducing the bug?

**Comment by Lim-Sung-Jun** [comment]
> @Lim-Sung-Jun Sorry I did not get you. Could you restate your question and provide instructions for reproducing the bug?

I solved this problem, thank you for your attention!

**Comment by Alizah-Masood** [comment]
> > @Lim-Sung-Jun Sorry I did not get you. Could you restate your question and provide instructions for reproducing the bug?
> 
> I solved this problem, thank you for your attention!

Hi, I'm having the same issue. Can you please specify how exactly you solved this problem?

**Comment by YangTakeshi** [comment]
> 
> 
> > > @Lim-Sung-Jun Sorry I did not get you. Could you restate your question and provide instructions for reproducing the bug?
> > 
> > 
> > I solved this problem, thank you for your attention!
> 
> Hi, I'm having the same issue. Can you please specify how exactly you solved this problem?

1. File "/IGMC/models.py", line 22:
    Change "num_features"  to  "num_node_features"
2. .File "/IGMC/util_functions.py", line 135:
    Change "def __len__(self)" to "def len(self)"
Then, you will solve this problem.

**Comment by Alizah-Masood** [comment]
Thanks. I did figure it out.

**Comment by Alizah-Masood** [comment]
> Thanks. I did figure it out.



> > > > @Lim-Sung-Jun Sorry I did not get you. Could you restate your question and provide instructions for reproducing the bug?
> > > 
> > > 
> > > I solved this problem, thank you for your attention!
> > 
> > 
> > Hi, I'm having the same issue. Can you please specify how exactly you solved this problem?
> 
> 1. File "/IGMC/models.py", line 22:
>    Change "num_features"  to  "num_node_features"
> 2. .File "/IGMC/util_functions.py", line 135:
>    Change "def __len__(self)" to "def len(self)"
>    Then, you will solve this problem.

Thanks! I did figure it out.
