### ISSUE TITLE
rating prediction for new datasets

### ISSUE THREAD

**Issue by technophyte** [muhanzhang/IGMC#26]
I am trying to apply this code for two different settings:
1. when predicting 1 (or 0) instead of ratings 1-5.
2. when predicting non-standardized ratings as either continuous or larger number of classes

Has this method been tested for predicting ratings for the above cases? If yes, what are your suggestions?

**Comment by muhanzhang** [comment]
Hi! For ratings other than 1-5, yes, IGMC totally supports them (the Flixter, Yahoo Music both do not use standard 1-5 ratings). You can write your own data loading function, as this [function](https://github.com/muhanzhang/IGMC/blob/5fa0e3cb1bdc46ffcb97fa6e0249a553e2e0b438/Main.py#L233) shows. No matter how many discrete ratings you have (e.g., the Yahoo Music used in the paper has 100 ratings), they are first transformed to classes 0, 1, 2, ..., and `class_values` record the true rating of each class. Later these rating classes are transformed back to true ratings in [IGMC data loader](https://github.com/muhanzhang/IGMC/blob/5fa0e3cb1bdc46ffcb97fa6e0249a553e2e0b438/util_functions.py#L208) and IGMC treats rating prediction as a regression problem.

For continuous ratings, you can skip the intermediate step that transforms true ratings to class labels and then transforms them back, but directly record the true ratings.

**Comment by technophyte** [comment]
Thanks a lot for your prompt response. I have a follow-up question:

Suppose the user-item information is only limited to having 1s (only one type of rating). Do you think IGMC would still be applicable especially if neither the train nor test data comprise any other edges (unlike 2s, 3s etc., as rating) and 0s are by default ignored? Or should I explicitly include some of the 0s (and then increment these data points by 1 to have at least two types of ratings, finally)?

**Comment by muhanzhang** [comment]
Then the problem reduces to a link prediction problem in homogeneous networks. You may use [SEAL](https://github.com/muhanzhang/SEAL) for it. Negative links (0s) are sampled randomly from the network, and a classifier is trained to separate positive links (1s) from negative links (0s).

**Comment by technophyte** [comment]
Thanks again for your response! I will look into link prediction.
