### ISSUE TITLE
Possibilities of adding side features?

### ISSUE THREAD

**Issue by jasperhyp** [muhanzhang/IGMC#30]
Hi,  Thanks for constantly maintaining this repo.  I understand that this paper mainly focuses on the situation without side information, but in the experiments, IGMC seems to outperform many other models with side features.  If we do have some side information (say, we have user features but not item features), can we add those features in a meaningful way to IGMC?  Or could you recommend some other recent works in this regard (inductive recommendation w/ some side features)?  Thanks in advance!

**Comment by muhanzhang** [comment]
Yes, you can use side features in IGMC. I have tried several ways (such as only using the target user and item's features) but they do not work better, though I didn't go into it deeply. You can check how I leverage side features in this [block of code](https://github.com/muhanzhang/IGMC/blob/5fa0e3cb1bdc46ffcb97fa6e0249a553e2e0b438/util_functions.py#L255-L275). Uncomment/comment the True/False to switch between different ways. And you also need to append "--use-feature" to your command. You may also need to modify the GNN code to adapt to process features with different shapes.
