### ISSUE TITLE
visualize is failing on higher epoch and even the ratings are getting other values apart from the class_labels of [0,1] as epoch are increased

### ISSUE THREAD

**Issue by sagar-nyamagouda** [muhanzhang/IGMC#32]
I am trying to solve a binary matrix completion problem using IGMC Algorithm. I have kept only 2 ratings [0,1].  When I feed the data of 0 and 1 labels, create a train test split, and run the code end to end it works fine but provided the epoch I limit it to 20. so when the epoch is kept at 20, the algorithm also works and the visualize also works fine and graphs are generated, but as the epoch is increased to 30 or 40 the training ensemble code runs fine and in the edge attributes there are different labels assigned apart from 0 and 1 such as 2, 3, 4 due to which the visualize option is failing with index error 
```
edge_types = [class_values[edge_types[x]] for x in g.edges()]
IndexError: index 2 is out of bounds for axis 0 with size 2
```
Please let me know if I am missing something or need to understand some code behavior or if can I apply such a binary matrix completion problem with the IGMC algorithm in the first place.

**Comment by muhanzhang** [comment]
I am not sure what is going wrong. Can you try to disable ensemble and then try everything again? Also, more bug reports help me to locate the problem.

**Comment by sagar-nyamagouda** [comment]
I changed my problem a little bit now, I have used a probability value on a scale of 1 to 10[converted the probability value onto the scale of 10]. I am not converting to the standard ratings. when I train the model now the same error is occurring again

Stack trace:
```
class values are as follows

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Traceback (most recent call last):
  File "C:\Users\sagarnya\PycharmProjects\IGMC\Main.py", line 436, in <module>
    visualize(
  File "C:\Users\sagarnya\PycharmProjects\IGMC\train_eval.py", line 305, in visualize
    edge_types = [class_values[edge_types[x]] for x in g.edges()]
  File "C:\Users\sagarnya\PycharmProjects\IGMC\train_eval.py", line 305, in <listcomp>
    edge_types = [class_values[edge_types[x]] for x in g.edges()]
IndexError: index 16 is out of bounds for axis 0 with size 11
```

I am basically reading a CSV file that has 2 node information and 3rd column as their interaction value which represents the probability similar to rating. Then in the pre-processing step, I am creating an adjacency matrix as other datasets are created and then feed this data to the model for learning.

**Comment by muhanzhang** [comment]
What's the command you use? I need to know the specific hyperparameters.

Also, can you check the adjacency matrix created to see whether it accidentally includes some numbers out of the range 0-10. Also, check whether the testing subgraphs contain edge types larger than the training edges. In IGMC we need to ensure all the possible ratings are seen during training.

**Comment by sagar-nyamagouda** [comment]
```
Tried these commands to use with ensemble option
python Main.py --data-name openmlV2 --epochs 30  --ensemble
python Main.py --data-name openmlV2 --epochs 20 --testing --ensemble

Tried this option without ensemble option
python Main.py --data-name openmlV2 --epochs 30 --testing

Ran command to visualize the results
python Main.py --data-name openmlV2 --epochs 30 --testing --no-train --visualize
```
I did not run any specific hyperparameters, using the defaults one
In the actual CSV file, I have probabilities in the range of 0-1 and these probabilities I am multiplying these by 10 and converting them in the rating of 1-10. 
I printed the train, test and Val labels they look fine to me there is no other rating in the out-of-range 1-10
```
print results
train_labels are [ 0  1  2  3  4  5  6  7  8  9 10]
test_labels are [ 0  1  2  3  4  5  6  7  8  9 10]
Validation labels are [ 0  1  2  3  4  5  6  7  8  9 10]
```
I am directly reading a CSV file and build train_test_split through the function that is present

**Comment by muhanzhang** [comment]
I mean not only train/val/test labels, but also the actual values in the adjacency matrices. They are used as edge features input to the R-GCN. From the traceback:
`File "C:\Users\sagarnya\PycharmProjects\IGMC\train_eval.py", line 305, in <listcomp>
    edge_types = [class_values[edge_types[x]] for x in g.edges()]
IndexError: index 16 is out of bounds for axis 0 with size 11`
It is some extracted subgraph containing edges whose edge types are out of [1-10]. You can locate this subgraph by running the code in ipython's pdb mode and print these edge types to locate the issues.

**Comment by sagar-nyamagouda** [comment]
Thanks @muhanzhang I was able to find the root cause, this issue was occurring because I had such value labels in the adjacency matrix. This was occurring while constructing the CSR matrix, since the dataset had duplicate records.

**Comment by sagar-nyamagouda** [comment]
The issue was resolved by removing duplicate records from the dataset
