### ISSUE TITLE
a issue about paper

### ISSUE THREAD

**Issue by naivefaith** [muhanzhang/IGMC#4]
hi,although the model use differet label to distinguish user node and item node,the two type of node have different feature.how RCGN aggregate two type of feature?besides if the label also is feature that take part in convolution operation?thank you.

**Comment by muhanzhang** [comment]
Hi, the node labels are indeed features used in graph convolution. And in IGMC, we by default do not use other continuous node features for convolution. That is, the one-hot encoding of these integer node labels (0 for center user, 1 for center item, 2i for user i hop away, 2i+1 for item i hop away) are the only used features for convolution, which achieves the purpose of inductive matrix completion without using content feature. 

If you do want to use content features, IGMC supports this by concatenating only the content features of target user and target item with the GNN-learned subgraph representation together, before feeding into the final MLP for rating prediction.

Your suggestion of using a bipartite GNN that handles different node types using different convolution weights is welcome, although I have not tried it myself. It might work better than using node labels to distinguish users/items.
