### ISSUE TITLE
Is it available transform to 'DGL'?

### ISSUE THREAD

**Issue by hjlee9182** [muhanzhang/IGMC#5]
'IGMC' is very awesome paper about recommendation system!

I'm a 'DGL' user , so I want to transform to this library to "DGL".
Is it available? or Do you have a plan about production of this paper which 'DGL' version.

**Comment by muhanzhang** [comment]
Thanks! Currently I don't have a plan to transform it to DGL. Please feel free to contribute or let me know if you find a DGL implementation!

**Comment by swtheing** [comment]
I have transformed IGMC to DGL, https://github.com/swtheing/IGMC_DGL.

**Comment by swtheing** [comment]
I have transformed IGMC to DGL, https://github.com/swtheing/IGMC_DGL. I hope it could help you.
