### ISSUE TITLE
About large-scale experiments

### ISSUE THREAD

**Issue by Junshuai-Song** [muhanzhang/IGMC#9]
Dear authors,
Recently I am doing subgraph-based GNN experiments on large-scale graphs. But I found that it is difficult to pre-process subgraphs around edges on a large-scale bipartite graph.
Could you please give some suggestions? Thanks.

Regards,

**Comment by muhanzhang** [comment]
Can you give some messages or logs about where the problem is? Is it due to slow processing speed, OOM, or out of disk space? There are many ways to accelerate IGMC on large-scale graphs, such as tuning '--max-train-num', '--max-nodes-per-hop', etc.

**Comment by Junshuai-Song** [comment]
Thanks for your quick reply.
My question is: when dealing with large-scale bipartite graphs, I cannot pre-build a sparse adj matrix on a machine.
Related codes in your preprocessing.py file from line 202 to 208 are:
    # make training adjacency matrix
    rating_mx_train = np.zeros(num_users * num_items, dtype=np.float32)
    if post_rating_map is None:
        rating_mx_train[train_idx] = labels[train_idx].astype(np.float32) + 1.
    else:
        rating_mx_train[train_idx] = np.array([post_rating_map[r] for r in class_values[labels[train_idx]]]) + 1.
    rating_mx_train = sp.csr_matrix(rating_mx_train.reshape(num_users, num_items))

**Comment by Junshuai-Song** [comment]
For example, I have 1 million users and 10 millions items.

**Comment by muhanzhang** [comment]
Hi! Thanks for raising this issue. The original preprocessing script is copied from the GCMC code, which doesn't consider the issue of scaling to super large graphs. Now I have changed rating_mx_train to be directly created in sparse matrix form, without the need to create a dense np.zeros() matrix. See [here](https://github.com/muhanzhang/IGMC/blob/f370c87108f1c3233afd9c5b10efe4668d4c6cc9/preprocessing.py#L207). Can you try your dataset again with the latest version?

**Comment by Junshuai-Song** [comment]
Very appreciated for your help. I will try it.

**Comment by Junshuai-Song** [comment]
Dear Zhang,
I tried a bipartite graph with 5W users, 50W items and 2000W edges. The code works well when I directly create rating_mx_train in sparse matrix form as you suggested. Thanks again.
I will close this issue.

Regards,

**Comment by suhmily** [comment]
I met same problem on large graph , related code in preprocessing.py on line 156:
labels = np.full((num_users, num_items), neutral_rating, dtype=np.int32)
Could you please give some suggestions? Thanks.

**Comment by muhanzhang** [comment]
> I met same problem on large graph , related code in preprocessing.py on line 156:
> labels = np.full((num_users, num_items), neutral_rating, dtype=np.int32)
> Could you please give some suggestions? Thanks.

Answered in #14. Sorry I only noticed the rating matrix issue last time, without seeing that the label matrix is also in dense form. Now it should be ok.
